# Generated by Django 5.0.6 on 2024-05-29 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='support',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='support',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='support',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='support',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='support',
            name='user',
        ),
        migrations.AddField(
            model_name='admin',
            name='type',
            field=models.CharField(default='Admin', editable=False),
        ),
        migrations.AddField(
            model_name='developer',
            name='type',
            field=models.CharField(default='Admin', editable=False),
        ),
        migrations.AddField(
            model_name='support',
            name='type',
            field=models.CharField(default='Admin', editable=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='support',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
