# Generated by Django 5.0.6 on 2024-05-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_admin_created_at_remove_admin_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
